# Generated by Django 2.2 on 2021-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housetitle', models.CharField(max_length=255)),
                ('houseaddress', models.CharField(max_length=255)),
                ('houseprice', models.CharField(max_length=255)),
                ('housearea', models.CharField(max_length=255)),
                ('housedescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RentHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housetitle', models.CharField(max_length=255)),
                ('houseaddress', models.CharField(max_length=255)),
                ('houseprice', models.CharField(max_length=255)),
                ('housearea', models.CharField(max_length=255)),
                ('housedescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SecondHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housetitle', models.CharField(max_length=255)),
                ('houseaddress', models.CharField(max_length=255)),
                ('houseprice', models.CharField(max_length=255)),
                ('housearea', models.CharField(max_length=255)),
                ('housedescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
